/* 常驻疑似位置复核：真实隧道录像、人工示例、逐点停帧、快速采集及原有操作兼容。 */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const cases=require('./tunnel-video-cases.json'),out=path.join(__dirname,'output');
const file=c=>{const published=path.join(__dirname,'..','assets','videos',c.playbackFile||c.file);return fs.existsSync(published)?published:path.join(out,'public-videos',c.playbackFile||c.file);};
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:1080},reducedMotion:'reduce'}),checks=[],errors=[];
 const pass=name=>{checks.push({name});console.log('PASS '+name)};
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 const state=()=>page.evaluate(()=>SLZJ.snapshot()),scene=()=>page.evaluate(()=>document.querySelector('#twinFrame').contentWindow.SLZJScene.snapshot());
 const seek=async time=>{await page.locator('#monitorVideo').evaluate((v,time)=>{v.pause();v.currentTime=time},time);await page.waitForFunction(t=>{const v=document.querySelector('#monitorVideo');return !v.seeking&&Math.abs(v.currentTime-t)<.02},time)};
 const align=async r=>{await page.waitForFunction(r=>{const s=document.querySelector('#twinFrame').contentWindow.SLZJScene.snapshot();return s.selectedId===r.id&&Math.abs(s.carX-r.position.x)<.04},r);};
 const load=async c=>{
  await page.locator('#monitorFile').setInputFiles(file(c));await page.waitForFunction(()=>TunnelVideoMonitor.evidenceIdentity().ready&&TunnelVideoMonitor.evidenceIdentity().sourceId);
  await page.locator('#taskLoadPositionExample').waitFor({state:'visible'});await page.locator('#taskLoadPositionExample').click();
  await page.waitForFunction(()=>document.querySelector('#taskLoadPositionExample').textContent.includes('载入')&&document.querySelector('#taskPositionMessage').textContent.includes('已载入'),null,{timeout:90000});
  const sid=await page.evaluate(()=>TunnelVideoMonitor.evidenceIdentity().sourceId);
  return (await state()).evidenceRecords.filter(r=>r.anchors.some(a=>a.sourceId===sid)).sort((a,b)=>a.anchors[0].timeSec-b.anchors[0].timeSec);
 };
 try{
  await page.goto('http://127.0.0.1:8765/index.html#tasks');await page.waitForFunction(()=>document.querySelector('#twinFrame')?.contentWindow?.SLZJScene,null,{timeout:60000});
  assert.equal(await page.locator('#taskEvidenceDrawer').getAttribute('open'),null);assert(await page.locator('#taskPositionReview').isVisible());pass('疑似位置栏常驻，证据抽屉折叠时仍有复核入口');
  assert.equal((await state()).evidenceRecords.length,0);const original=(await state()).defects;assert(await page.locator('#taskQuickMark').isDisabled());pass('未接入画面时不生成或标记空证据');
  await page.locator('#monitorFile').setInputFiles(file(cases[2]));await page.waitForFunction(()=>TunnelVideoMonitor.evidenceIdentity().ready&&TunnelVideoMonitor.evidenceIdentity().sourceId);
  assert.equal((await state()).evidenceRecords.length,0);assert.match(await page.locator('#taskPositionMessage').textContent(),/人工|不是自动/);pass('识别完整文件指纹后只提示人工示例，不静默添加假病害');
  await seek(8);await page.locator('#taskFollowVideo').check();await page.waitForFunction(()=>{const v=document.querySelector('#monitorVideo');return Math.abs(document.querySelector('#twinFrame').contentWindow.SLZJScene.snapshot().carX-48*v.currentTime/v.duration)<.04});
  assert.equal((await state()).evidenceRecords.length,0);pass('常驻栏联动开关在无标注时仍驱动车辆');
  let records=await load(cases[2]);assert.equal(records.length,3);assert.deepEqual(records.map(r=>r.anchors[0].timeSec),[10,14,18]);assert(records.every(r=>r.type===null&&r.classificationStatus==='pending'));pass('公路隧道原拍摄段载入3个人工位置，保持未分类和出现顺序');
  assert(records.every(r=>r.anchors[0].thumbnail.startsWith('data:image/jpeg;base64,')&&r.positionBasis.includes('人工预选')));await align(records[0]);assert.equal(await page.locator('.monitor-evidence-point').textContent(),'1');pass('示例从当前原录像取真实缩略帧，载入后立即显示首个原帧与仿真定位点');
  await page.locator(`.position-review-point[data-id="${records[1].id}"]`).click();await align(records[1]);assert(Math.abs(await page.locator('#monitorVideo').evaluate(v=>v.currentTime)-14)<.02);
  assert.equal(await page.locator('.monitor-evidence-point').textContent(),'2');assert.equal(await page.locator('#taskPositionCue').getAttribute('data-current-id'),records[1].id);assert.equal((await scene()).positions.find(p=>p.id===records[1].id).sequence,2);pass('点击顺序编号同步回到原帧，画面编号、仿真编号、里程与XYZ一致');
  await page.evaluate(()=>scrollTo(0,scrollY+document.querySelector('#taskPositionReview').getBoundingClientRect().top-85));await page.screenshot({path:path.join(out,'疑似位置复核-左右对应.png')});
  await seek(15);assert.equal(await page.locator('.monitor-evidence-point').count(),0);assert.equal(await page.locator('.position-review-point').count(),3);assert.match(await page.locator('#taskPositionCue').textContent(),/下一处 #3/);pass('离开原帧后隐藏像素点，常驻顺序条和下一处提示仍可见');
  await page.locator('#taskLoadPositionExample').click();await page.waitForFunction(()=>document.querySelector('#taskPositionMessage').textContent.includes('未重复'));assert.equal((await state()).evidenceRecords.length,3);pass('重复载入不会重复记录或删除已有位置');
  for(const c of cases.slice(0,2)){
   records=await load(c);assert.equal(records.length,3);assert.deepEqual(records.map(r=>r.anchors[0].timeSec),c.points.map(p=>p.time));
   assert(records.every(r=>r.type===null));assert.equal(await page.locator('.position-review-point').count(),3);assert.deepEqual((await scene()).visibleIds.slice().sort(),records.map(r=>r.id).sort());
   for(const r of records){await page.locator(`.position-review-point[data-id="${r.id}"]`).click();await align(r);const p=(await scene()).positions.find(p=>p.id===r.id);assert(p.markerOnly&&p.type==='suspected');for(const k of ['x','y','z'])assert(Math.abs(p[k]-r.position[k])<.00001);}
   pass('同源视频3处顺序及原帧/车/仿真坐标对应且不混入其他视频：'+c.file);
  }
  await seek(0);await page.locator('#taskReviewStops').check();
  for(const r of records){
   await page.locator('#monitorVideo').evaluate(v=>v.play());await page.waitForFunction(time=>{const v=document.querySelector('#monitorVideo');return v.paused&&!v.seeking&&Math.abs(v.currentTime-time)<.02},r.anchors[0].timeSec,{timeout:12000});await align(r);
   assert.equal(await page.locator('#taskPositionCue').getAttribute('data-current-id'),r.id);
  }pass('连续播放按1/3/5秒先后逐点暂停到原帧，原视频与仿真疑似位置匹配');
  await page.locator('#taskReviewStops').uncheck();await seek(4);const old=records.map(r=>JSON.stringify(r));await page.locator('#taskQuickMark').click();await page.locator('.position-mark-dialog').waitFor({state:'visible'});
  assert(await page.locator('#positionMarkSave').isDisabled());assert.equal(await page.locator('.position-mark-dialog select').count(),0);pass('快速标记停在原帧，选点前不能保存且不要求病害类型');
  await page.locator('#positionReviewFrame').click({position:{x:180,y:140}});await page.locator('#positionMarkNote').fill('人工观察到的待复核位置');await page.screenshot({path:path.join(out,'疑似位置复核-快速标记.png')});await page.locator('#positionMarkSave').click();await page.locator('.position-mark-dialog').waitFor({state:'detached'});
  const current=(await state()).evidenceRecords,created=current.find(r=>r.anchors[0].sourceId===records[0].anchors[0].sourceId&&r.anchors[0].timeSec===4);assert(created&&created.type===null);assert(created.positionBasis.includes('人工观察'));await align(created);
  assert.equal(await page.locator('.position-review-point').count(),4);assert.equal(await page.locator('.monitor-evidence-point').textContent(),'3');assert(records.every((r,i)=>JSON.stringify(current.find(x=>x.id===r.id))===old[i]));pass('保存新的4秒位置插入正确顺序，并保留原有记录与相同编号的坐标');
  await page.locator('#taskEvidenceDrawer > summary').click();assert(await page.locator('#evidenceFollowVideo').isChecked());await page.locator('#evidenceFollowVideo').uncheck();assert(!(await page.locator('#taskFollowVideo').isChecked()));await page.locator('#taskFollowVideo').check();assert(await page.locator('#evidenceFollowVideo').isChecked());pass('原证据抽屉和新常驻开关共用联动状态，原标注/导入/导出组件保留');
  await page.locator('#taskEvidenceDrawer > summary').click();await page.locator('.scene-settings > summary').click();await page.locator('[data-action=roam]').click();await page.waitForFunction(()=>document.querySelector('#twinFrame').contentWindow.SLZJScene.snapshot().firstPerson);const frame=page.frames().find(f=>f.url().includes('tunnel-scene.html'));
  await page.locator(`.position-review-point[data-id="${records[1].id}"]`).click();await align(records[1]);assert.equal(page.frames().find(f=>f.url().includes('tunnel-scene.html')),frame);assert((await scene()).firstPerson);await page.keyboard.press('Escape');pass('位置复核不重建三维场景，第一人称和原控制组件保持');
  await page.locator('#taskComparison').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'疑似位置复核-1440.png')});await page.setViewportSize({width:390,height:1000});await page.evaluate(()=>scrollTo(0,scrollY+document.querySelector('#taskPositionReview').getBoundingClientRect().top-65));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.screenshot({path:path.join(out,'疑似位置复核-390.png')});pass('桌面与390像素手机布局无整页横向溢出，顺序条可独立滚动');
  await page.locator('#taskQuickMark').click();await page.locator('.position-mark-dialog').waitFor({state:'visible'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.locator('#positionReviewFrame').focus();await page.keyboard.press('ArrowRight');assert(!(await page.locator('#positionMarkSave').isDisabled()));await page.keyboard.press('Escape');assert.equal((await state()).evidenceRecords.length,current.length);pass('手机标记对话框可用键盘选点，取消不会写入位置');
  await page.setViewportSize({width:1440,height:1080});await page.reload();await page.waitForFunction(()=>document.querySelector('#twinFrame')?.contentWindow?.SLZJScene);assert.equal((await state()).evidenceRecords.length,current.length);
  await page.locator('#monitorFile').setInputFiles(file(cases[1]));await page.waitForFunction(()=>TunnelVideoMonitor.evidenceIdentity().ready&&TunnelVideoMonitor.evidenceIdentity().sourceId);assert.equal(await page.locator('.position-review-point').count(),4);pass('刷新后保留人工位置，重新导入原文件恢复常驻顺序条');
  await page.locator('#taskEvidenceDrawer').evaluate(d=>d.open=true);await page.locator(`#evidenceList [data-evidence-action=edit][data-id="${records[1].id}"]`).click();await page.locator('#evidenceMileage').fill('3152');await page.locator('[data-evidence-action=update]').click();
  await page.locator(`.position-review-point[data-id="${records[1].id}"]`).click();const manual=(await state()).evidenceRecords.find(r=>r.id===records[1].id);await align(manual);await page.waitForTimeout(550);assert(Math.abs((await scene()).carX-24)<.04);assert(!(await page.locator('#taskFollowVideo').isChecked()));assert.match(await page.locator('#taskPositionMessage').textContent(),/人工工程坐标/);assert.match(await page.locator('#taskPositionProgress').textContent(),/记录里程 3152.000/);pass('回看人工修订坐标时关闭相对进度覆盖，车辆保持修订位置');
  await page.locator('#taskQuickMark').click();await page.locator('.position-mark-dialog').waitFor({state:'visible'});await page.locator('#monitorFile').setInputFiles(file(cases[0]));await page.waitForFunction(()=>TunnelVideoMonitor.evidenceIdentity().ready&&TunnelVideoMonitor.evidenceIdentity().sourceId);assert.equal(await page.locator('.position-mark-dialog').count(),0);assert.equal((await state()).evidenceRecords.length,current.length);pass('标记期间更换视频自动取消原帧，防止跨源写入');
  const c0=(await state()).evidenceRecords.filter(r=>r.anchors[0].sourceId==='VF-'+cases[0].sha256);if(await page.locator('#taskEvidenceDrawer').getAttribute('open')===null)await page.locator('#taskEvidenceDrawer > summary').click();for(const r of c0)await page.locator(`#evidenceList [data-evidence-action=delete][data-id="${r.id}"]`).click();const beforeCancel=(await state()).evidenceRecords.length;
  await page.locator('#taskLoadPositionExample').click();await page.waitForFunction(()=>document.querySelector('#taskLoadPositionExample').textContent.includes('正在'));await page.locator('#monitorFile').setInputFiles(file(cases[2]));await page.waitForFunction(()=>TunnelVideoMonitor.evidenceIdentity().ready&&TunnelVideoMonitor.evidenceIdentity().sourceId);await page.waitForTimeout(300);assert.equal((await state()).evidenceRecords.length,beforeCancel);pass('批量取帧期间换源取消整次加载，没有半写入或删除其他来源');
  const changed=Buffer.concat([fs.readFileSync(file(cases[0])),Buffer.from([0])]);await page.locator('#monitorFile').setInputFiles({name:cases[0].file,mimeType:'video/mp4',buffer:changed});await page.waitForFunction(()=>TunnelVideoMonitor.evidenceIdentity().ready&&TunnelVideoMonitor.evidenceIdentity().sourceId);assert(await page.locator('#taskLoadPositionExample').isHidden());assert.equal(await page.locator('.position-review-point').count(),0);assert.equal((await state()).evidenceRecords.length,beforeCancel);pass('同文件名但不同内容的录像不能冒用已复核示例位置');
  assert.deepEqual((await state()).defects,original);pass('新位置与示例不改写原有16处演示病害台账');assert.deepEqual(errors,[]);pass('位置复核全流程无页面或控制台异常');
  fs.writeFileSync(path.join(out,'position-review-results.json'),JSON.stringify({checkedAt:new Date().toISOString(),checks,errors,videos:cases.map(c=>c.playbackFile||c.file),boundary:'3段真实隧道检测录像的人工待复核位置；相对映射验证顺序和坐标，不做病害真值、自动识别或实测定位精度结论。'},null,2));console.log('ALL '+checks.length+' POSITION REVIEW CHECKS PASSED');
 }catch(error){console.error("POSITION REVIEW STATE",await page.evaluate(()=>({message:document.querySelector("#taskPositionMessage")?.textContent,identity:TunnelVideoMonitor.evidenceIdentity(),time:document.querySelector("#monitorVideo")?.currentTime,seeking:document.querySelector("#monitorVideo")?.seeking,load:document.querySelector("#taskLoadPositionExample")?.textContent,records:SLZJ.snapshot().evidenceRecords.length})));throw error;}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});