const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const http = require('http');
const out = path.resolve(__dirname, 'output');
fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader','--use-fake-device-for-media-stream','--disable-background-timer-throttling','--disable-renderer-backgrounding'] });
  let server;
  const checks = [], errors = [];
  const pass = (name, data) => { checks.push({name,...data}); console.log('PASS',name,data ? JSON.stringify(data) : ''); };
  try {
    const context = await browser.newContext({ viewport: {width:1440,height:1100}, acceptDownloads:true });
    await context.grantPermissions(['camera'], {origin:'http://127.0.0.1:8765'});
    const page = await context.newPage();
    await page.addInitScript(() => { window.__SLZJ_DISABLE_AUTO_INFERENCE__ = true; });
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://127.0.0.1:8765/index.html#tasks');
    await page.waitForSelector('#videoMonitor');
    const order = await page.locator('.task-page-layout .panel-head h2').allTextContents();
    assert.deepEqual(order.slice(0,5), ['项目设备示意','检测车作业场景 · 现场视频','现场疑似位置 · 视频 / 雷达 ↔ 仿真 ↔ 孪生','检测车作业场景 · 三维作业对照','任务列表']);
    assert.equal(await page.locator('#monitorEmpty').isVisible(),true);
    pass('设备折叠区、左右对照工作区、病害对应和任务列表完整，空状态正确');
    const fixturePage=await context.newPage();
    await fixturePage.addInitScript(() => { window.__SLZJ_DISABLE_AUTO_INFERENCE__ = true; });
    await fixturePage.bringToFront();
    const fixture = await fixturePage.evaluate(async () => {
      const canvas=document.createElement('canvas'); canvas.width=320;canvas.height=180;
      document.body.appendChild(canvas);
      const ctx=canvas.getContext('2d');
      ctx.fillStyle='#156750';ctx.fillRect(0,0,320,180);
      const stream=canvas.captureStream(0), track=stream.getVideoTracks()[0];
      const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'});
      const chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);
      const ended=new Promise(r=>recorder.onstop=r);recorder.start(100);
      for (let n=0;n<24;n++) {
        ctx.fillStyle=n%2?'#286aa1':'#156750';ctx.fillRect(0,0,320,180);
        ctx.fillStyle='#fff';ctx.font='30px sans-serif';ctx.fillText('TEST FRAME '+n,30,90);
        track.requestFrame();await new Promise(r=>setTimeout(r,90));
      }
      recorder.stop();await ended;stream.getTracks().forEach(t=>t.stop());
      const blob=new Blob(chunks,{type:'video/webm'});
      const jpeg=await new Promise(r=>canvas.toBlob(r,'image/jpeg'));
      return { video:Array.from(new Uint8Array(await blob.arrayBuffer())), jpeg:Array.from(new Uint8Array(await jpeg.arrayBuffer())) };
    });
    await fixturePage.close();await page.bringToFront();
    assert(fixture.video.length>500,'Generated fixture must contain encoded frames');
    fs.writeFileSync(path.join(out,'monitor-test.webm'),Buffer.from(fixture.video));
    const before = await page.evaluate(()=>SLZJ.snapshot());
    await page.locator('#monitorFile').setInputFiles({name:'现场测试录像.webm',mimeType:'video/webm',buffer:Buffer.from(fixture.video)});
    await page.waitForFunction(()=>document.querySelector('#monitorVideo').videoWidth===320 && !document.querySelector('[data-monitor-action=capture]').disabled);
    assert.match(await page.locator('#monitorSourceBadge').textContent(),/回放/);
    assert.equal(await page.locator('#monitorResolution').textContent(),'320 × 180');
    const after = await page.evaluate(()=>SLZJ.snapshot());
    assert.deepEqual(after.defects,before.defects);assert.deepEqual(after.assessment,before.assessment);
    await page.locator('#monitorVideo').evaluate(v=>v.pause());
    const position=await page.locator('#monitorVideo').evaluate(v=>v.currentTime);
    pass('本地文件实际解码播放，录像标识明确且未污染病害和SHI');
    const capturePromise=page.waitForEvent('download');
    await page.locator('[data-monitor-action=capture]').click();
    const capture=await capturePromise;
    await capture.saveAs(path.join(out,'video-capture.png'));
    const bytes=fs.readFileSync(path.join(out,'video-capture.png'));
    assert.equal(bytes.readUInt32BE(16),320);assert.equal(bytes.readUInt32BE(20),180);
    const recordPromise=page.waitForEvent('download');await page.locator('[data-monitor-action=record]').click();
    const record=await recordPromise;await record.saveAs(path.join(out,'video-record.json'));
    const entry=JSON.parse(fs.readFileSync(path.join(out,'video-record.json'),'utf8'));
    assert.equal(entry.current.kind,'file');assert.equal(entry.association.batchId,'B202609');assert.equal(entry.captures.length,1);
    assert(entry.captures[0].file.endsWith('.png'));
    pass('截图来自实际视频帧，导出记录关联来源、任务和批次');
    await page.locator('#monitorFile').setInputFiles({name:'invalid.txt',mimeType:'text/plain',buffer:Buffer.from('not video')});
    assert.match(await page.locator('#monitorFeedback').textContent(),/视频文件/);
    assert.equal(await page.locator('#monitorResolution').textContent(),'320 × 180');
    await page.locator('[data-monitor-mode=network]').click();
    await page.locator('#monitorURL').fill('rtsp://127.0.0.1/camera');
    await page.locator('#monitorNetworkForm button[type=submit]').click();
    assert.match(await page.locator('#monitorFeedback').textContent(),/RTSP/);
    assert.match(await page.locator('#monitorSourceBadge').textContent(),/回放/);
    pass('非法文件和RTSP地址明确拒绝，不中断已接入录像');
    await page.locator('#taskSpeed').fill('0.7');await page.locator('#taskForm button[type=submit]').click();
    await page.waitForSelector('#monitorResolution', {state:'attached'});
    assert.equal(await page.locator('#monitorResolution').textContent(),'320 × 180');
    assert(Math.abs((await page.locator('#monitorVideo').evaluate(v=>v.currentTime))-position)<.1);
    pass('应用作业参数保留视频来源和进度');
    await page.evaluate(()=>{location.hash='radar';});await page.waitForSelector('#csvFile');
    await page.evaluate(()=>{location.hash='tasks';});await page.waitForSelector('#monitorVideo');
    assert.equal(await page.locator('#monitorVideo').evaluate(v=>v.paused),true);
    assert.equal(await page.locator('#monitorResolution').textContent(),'320 × 180');
    pass('路由往返暂停并保留本地录像，不会误标成实时');
    await page.locator('[data-monitor-mode=network]').click();
    await page.locator('#monitorURL').fill('http://127.0.0.1:8765/tests/output/monitor-test.webm');
    await page.locator('#monitorNature').selectOption('recording');
    await page.locator('#monitorNetworkForm button[type=submit]').click();
    await page.waitForFunction(()=>document.querySelector('#monitorVideo').videoWidth===320 && !document.querySelector('[data-monitor-action=capture]').disabled);
    assert.match(await page.locator('#monitorSourceBadge').textContent(),/网络录像/);
    pass('HTTP外部视频直链实际播放并标记来源');
    let socketCount=0;
    server=http.createServer((req,res)=>{
      if (req.url!=='/live.mjpeg') {res.writeHead(404);res.end();return;}
      socketCount++;
      res.writeHead(200,{'Content-Type':'multipart/x-mixed-replace; boundary=frame','Cache-Control':'no-store'});
      const jpeg=Buffer.from(fixture.jpeg);
      const interval=setInterval(()=>{
        res.write('--frame\r\nContent-Type: image/jpeg\r\nContent-Length: '+jpeg.length+'\r\n\r\n');res.write(jpeg);res.write('\r\n');
      },80);
      req.on('close',()=>{socketCount--;clearInterval(interval);});
    });
    await new Promise(r=>server.listen(0,'127.0.0.1',r));
    await page.locator('#monitorURL').fill(`http://127.0.0.1:${server.address().port}/live.mjpeg`);
    await page.locator('#monitorFormat').selectOption('mjpeg');await page.locator('#monitorNature').selectOption('live');
    await page.locator('#monitorNetworkForm button[type=submit]').click();
    await page.waitForFunction(()=>document.querySelector('#monitorStatus').textContent==='监测中',null,{timeout:12000});
    assert.equal(await page.locator('#monitorImage').evaluate(i=>i.naturalWidth),320);
    await page.locator('[data-monitor-action=capture]').click();
    await page.waitForFunction(()=>document.querySelector('#monitorFeedback').textContent.includes('跨域'));
    assert.equal(await page.locator('#monitorStatus').textContent(),'监测中');
    pass('跨域MJPEG可观看，取证受限时给出明确提示');
    await page.locator('[data-monitor-action=stop]').click();
    await page.waitForTimeout(200);
    assert.equal(socketCount,0);
    pass('MJPEG持续流真实接收，停止后断开连接');
    await page.locator('#monitorNature').selectOption('recording');
    await page.locator('#monitorNetworkForm button[type=submit]').click();
    await page.waitForFunction(()=>document.querySelector('#monitorStatus').textContent==='回放中');
    assert.match(await page.locator('#monitorSourceBadge').textContent(),/网络录像/);
    assert.equal(await page.locator('#monitorTime').textContent(),'图像流 / 无录像进度');
    await page.locator('[data-monitor-action=stop]').click();
    pass('MJPEG录像遵循源端用途标为回放，不混用实时输入标识');
    await page.locator('[data-monitor-mode=camera]').click();
    await page.locator('[data-monitor-action=camera]').click();
    await page.waitForFunction(()=>document.querySelector('#monitorVideo').srcObject?.getVideoTracks()[0]?.readyState==='live' && document.querySelector('#monitorStatus').textContent==='监测中');
    await page.evaluate(()=>{window.testStream=document.querySelector('#monitorVideo').srcObject;});
    assert.equal(await page.evaluate(()=>testStream.getAudioTracks().length),0);
    pass('摄像头真实MediaStream接入，只采集视频（自动化虚拟设备）');
    await page.locator('[data-action=toggle-task]').click();
    await page.waitForFunction(()=>document.querySelector('#monitorVideo').srcObject?.active);
    const vtime=await page.locator('#monitorVideo').evaluate(v=>v.currentTime);
    await page.waitForTimeout(250);
    assert((await page.locator('#monitorVideo').evaluate(v=>v.currentTime))>vtime);
    await page.locator('[data-action=toggle-task]').click();
    assert.equal(await page.evaluate(()=>testStream.active),true);
    pass('仿真启停与摄像头播放独立');
    await page.locator('#taskSpeed').fill('0.6');await page.locator('#taskForm button[type=submit]').click();
    assert.equal(await page.evaluate(()=>document.querySelector('#monitorVideo').srcObject===testStream),true);
    pass('同任务页面刷新保留同一摄像头，不重新请求权限');
    await page.locator('#batch').selectOption('B202607');
    await page.waitForFunction(()=>window.testStream.getTracks().every(t=>t.readyState==='ended'));
    assert.equal(await page.locator('#monitorStatus').textContent(),'未接入');
    const changedRecordPromise=page.waitForEvent('download');
    await page.locator('[data-monitor-action=record]').click();
    const changedRecord=await changedRecordPromise;
    const changedRecordPath=await changedRecord.path();
    const changedRecordData=JSON.parse(fs.readFileSync(changedRecordPath,'utf8'));
    assert.equal(changedRecordData.association.batchId,'B202607');
    assert.equal(changedRecordData.current.sessionStart,null);
    assert.deepEqual(changedRecordData.captures,[]);
    assert.deepEqual(changedRecordData.events,[]);
    pass('切换批次释放原视频并清除旧取证记录，防止关联到错误任务');
    await page.locator('[data-monitor-mode=camera]').click();await page.locator('[data-monitor-action=camera]').click();
    await page.waitForFunction(()=>document.querySelector('#monitorVideo').srcObject?.active);
    await page.evaluate(()=>{window.testStream=document.querySelector('#monitorVideo').srcObject;location.hash='radar';});
    await page.waitForFunction(()=>testStream.getTracks().every(t=>t.readyState==='ended'));
    pass('离开检测页释放全部摄像头轨道');
    await page.evaluate(()=>{location.hash='tasks';});await page.waitForSelector('#videoMonitor');
    for(const width of [1024,768,390]){
      await page.setViewportSize({width,height:1000});
      const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);
      assert.equal(overflow,false);pass('新视频区无整页横向溢出',{width});
    }
    await page.setViewportSize({width:1440,height:1100});
    await page.locator('#videoMonitor').screenshot({path:path.join(out,'现场视频区.png')});
    await page.evaluate(()=>{
      const native=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
      window.originalCapture=native;
      navigator.mediaDevices.getUserMedia=async (constraints)=>{
        const stream=await native(constraints);window.lateStream=stream;
        await new Promise(r=>setTimeout(r,600));return stream;
      };
    });
    await page.locator('[data-monitor-mode=camera]').click();
    await page.locator('[data-monitor-action=camera]').click();
    await page.waitForFunction(()=>window.lateStream?.active);
    await page.evaluate(()=>{location.hash='radar';});
    await page.waitForFunction(()=>lateStream.getTracks().every(t=>t.readyState==='ended'));
    pass('权限异步返回期间离开页面，也会释放延迟到达的摄像头');
    await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=window.originalCapture;location.hash='tasks';});
    await page.waitForSelector('#videoMonitor');
    await page.locator('[data-monitor-mode=file]').click();
    await page.locator('#monitorFile').setInputFiles({name:'corrupted.webm',mimeType:'video/webm',buffer:Buffer.from('not an actual media file')});
    await page.waitForFunction(()=>document.querySelector('#monitorStatus').textContent==='连接失败');
    assert.match(await page.locator('#monitorFeedback').textContent(),/解码|格式/);
    pass('无法解码的视频不显示成功状态');
    const cdp=await browser.newBrowserCDPSession();
    const ids=await cdp.send('Target.getBrowserContexts');
    await cdp.send('Browser.setPermission',{permission:{name:'camera'},setting:'denied',origin:'http://127.0.0.1:8765',browserContextId:ids.browserContextIds[0]});
    await page.locator('[data-monitor-mode=camera]').click();await page.locator('[data-monitor-action=camera]').click();
    await page.waitForFunction(()=>document.querySelector('#monitorStatus').textContent==='连接失败');
    assert.match(await page.locator('#monitorFeedback').textContent(),/权限/);
    pass('摄像头权限拒绝反馈明确，不伪造接入成功');
    assert.deepEqual(errors,[]);
    fs.writeFileSync(path.join(out,'video-monitor-results.json'),JSON.stringify({checks,errors,boundary:'测试录像为浏览器生成素材，摄像头为自动化虚拟设备，MJPEG为本机测试流；未验证现场设备。'},null,2));
    console.log(`ALL ${checks.length} VIDEO CHECKS PASSED`);
  } finally {
    if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}
    await browser.close();
  }
})().catch(e=>{console.error(e.stack||e);process.exit(1);});
